INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (1, "Project 1", "Category 1", 100, "9/29/19", "9/30/19");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (2, "Project 2", "Category 2", 200, "10/1/19", "10/5/19");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (3, "Project 3", "Category 3", 300, "10/1/19", "10/10/19");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (4, "Project 4", "Category 4", 400, "9/30/19", "10/6/19");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (5, "Project 5", "Category 5", 500, "9/30/19", "10/1/19");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (6, "Project 6", "Category 6", 600, "10/1/19", "10/6/19");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (7, "Project 7", "Category 7", 700, "9/29/19", "9/30/19");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (8, "Project 8", "Category 8", 800, "10/1/19", "10/4/19");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (9, "Project 9", "Category 9", 900, "9/30/19", "10/3/19");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (10, "Project 10", "Category 10", 1000, "10/1/19", "10/8/19");

-- INSERT INTO users (id, name, age) VALUES (1, "Andrew", 30);
-- INSERT INTO users (id, name, age) VALUES (2, "Jessica", 29);
-- INSERT INTO users (id, name, age) VALUES (3, "Sean", 31);
-- INSERT INTO users (id, name, age) VALUES (4, "Danielle", 29);
-- INSERT INTO users (id, name, age) VALUES (5, "Joe", 31);
-- INSERT INTO users (id, name, age) VALUES (6, "Jen", 31);
-- INSERT INTO users (id, name, age) VALUES (7, "Brian", 31);
-- INSERT INTO users (id, name, age) VALUES (8, "Mike", 50);
-- INSERT INTO users (id, name, age) VALUES (9, "Jon", 38);
-- INSERT INTO users (id, name, age) VALUES (10, "Ari", 35);
-- INSERT INTO users (id, name, age) VALUES (11, "Erin", 36);
-- INSERT INTO users (id, name, age) VALUES (12, "Miguel" 24);
-- INSERT INTO users (id, name, age) VALUES (13, "Tim", 59);
-- INSERT INTO users (id, name, age) VALUES (14, "Sue", 61);
-- INSERT INTO users (id, name, age) VALUES (15, "Mookie", 26);
-- INSERT INTO users (id, name, age) VALUES (16, "Javier", 32);
-- INSERT INTO users (id, name, age) VALUES (17, "Edgar", 27);
-- INSERT INTO users (id, name, age) VALUES (18, "Ed", 50);
-- INSERT INTO users (id, name, age) VALUES (19, "Carly", 25);
-- INSERT INTO users (id, name, age) VALUES (20, "Jorge", 18);
