INSERT INTO projects (title, category, funding_goal, start_date, end_date) VAL("Project 1", "Category 1", 100, "9/29/19", "9/30/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 2", "Category 2", 200, "10/1/19", "10/5/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 3", "Category 3", 300, "10/1/19", "10/10/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 4", "Category 4", 400, "9/30/19", "10/6/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 5", "Category 5", 500, "9/30/19", "10/1/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 6", "Category 6", 600, "10/1/19", "10/6/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 7", "Category 7", 700, "9/29/19", "9/30/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 8", "Category 8", 800, "10/1/19", "10/4/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 9", "Category 9", 900, "9/30/19", "10/3/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 10", "Category 10", 1000, "10/1/19", "10/8/19");

INSERT INTO users (name, age) VALUES ("Andrew", 30);
INSERT INTO users (name, age) VALUES ("Jessica", 29);
INSERT INTO users (name, age) VALUES ("Sean", 31);
INSERT INTO users (name, age) VALUES ("Danielle", 29);
INSERT INTO users (name, age) VALUES ("Joe", 31);
INSERT INTO users (name, age) VALUES ("Jen", 31);
INSERT INTO users (name, age) VALUES ("Brian", 31);
INSERT INTO users (name, age) VALUES ("Mike", 50);
INSERT INTO users (name, age) VALUES ("Jon", 38);
INSERT INTO users (name, age) VALUES ("Ari", 35);
INSERT INTO users (name, age) VALUES ("Erin", 36);
INSERT INTO users (name, age) VALUES ("Miguel" 24);
INSERT INTO users (name, age) VALUES ("Tim", 59);
INSERT INTO users (name, age) VALUES ("Sue", 61);
INSERT INTO users (name, age) VALUES ("Mookie", 26);
INSERT INTO users (name, age) VALUES ("Javier", 32);
INSERT INTO users (name, age) VALUES ("Edgar", 27);
INSERT INTO users (name, age) VALUES ("Ed", 50);
INSERT INTO users (name, age) VALUES ("Carly", 25);
INSERT INTO users (name, age) VALUES ("Jorge", 18);
